# SonarQube/SonarCloud Configuration File
sonar.projectKey=UO294431_EPI-DevorApp
sonar.projectName=EPI-DevorApp
sonar.projectVersion=1.0

# Source and Test directories
sonar.sources=backend/app,frontend/src,keras-api/main.py,keras-api/train_pipeline.py
sonar.tests=backend/tests,frontend/src/tests,keras-api/test_main.py

# Exclusions
sonar.exclusions=**/node_modules/**,**/android/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts

# Coverage Reports
sonar.python.coverage.reportPaths=backend/coverage.xml,keras-api/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
